#+TITLE:      Linux Exercises
#+AUTHOR:     Sivaram
#+OPTIONS:    H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc author:nil date:nil html-postamble:nil
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://thomasf.github.io/solarized-css/solarized-light.min.css" />

Anyone interested can do it.
* Exercise 9/5/17:
Login to the server with
User: tutorial
Password: tutorial
1. You can either ssh(secure shell) into the server or directly execute commands on the server.
2. To ssh from a Linux PC
#+BEGIN_SRC
$ ssh tutorial@<serverip>
#+END_SRC
Enter password.
3. To ssh from putty (Windows).
Install putty.
Enter ip address and use port 22.
Login as: tutorial and enter password
This exercise is just logging into Linux.
Bonus points: type the following command:
#+BEGIN_SRC
$ ls
#+END_SRC
and send me the output.
* Exercise 10/5/17:
Create folder with your name
Print the current working directory
Go to that folder
Print the current working directory
Create another folder
Go to that folder
Go to home
Commands to be used
Creating folder
#+BEGIN_SRC
$ mkdir <folder_name>
#+END_SRC
Changing folder
#+BEGIN_SRC
$ cd <folder_name>
#+END_SRC
Displaying current folder
#+BEGIN_SRC
$ pwd
#+END_SRC
Home folder usually represented as
#+BEGIN_SRC
~
#+END_SRC
If you have any doubts read the manual with
#+BEGIN_SRC
$ man <command_name>
#+END_SRC
else use a search engine.
