#+TITLE:      Linux Exercises
#+AUTHOR:     Sivaram
#+OPTIONS:    H:3 num:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc author:nil date:nil html-postamble:nil
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://thomasf.github.io/solarized-css/solarized-light.min.css" />

Anyone interested can do it.
* Exercise 9/5/17:
Login to the server with \\
User: tutorial \\
Password: tutorial
1. You can either ssh(secure shell) into the server or directly execute commands on the server.
2. To ssh from a Linux PC
#+BEGIN_SRC
$ ssh tutorial@<serverip>
#+END_SRC
Enter password.
3. To ssh from putty (Windows).
Install putty. \\
Enter ip address and use port 22. \\
Login as: tutorial and enter password \\
This exercise is just logging into Linux. \\
Bonus points: type the following command:
#+BEGIN_SRC
$ ls
#+END_SRC
and send me the output.
* Exercise 10/5/17:
Create folder with your name \\
Print the current working directory \\
Go to that folder \\
Print the current working directory \\
Create another folder \\
Go to that folder \\
Go to home \\
Commands to be used \\
Creating folder
#+BEGIN_SRC
$ mkdir <folder_name>
#+END_SRC
Changing folder
#+BEGIN_SRC
$ cd <folder_name>
#+END_SRC
Displaying current folder
#+BEGIN_SRC
$ pwd
#+END_SRC
Home folder usually represented as
#+BEGIN_SRC
~
#+END_SRC
If you have any doubts read the manual with
#+BEGIN_SRC
$ man <command_name>
#+END_SRC
else use a search engine.
* Exercise 11/5/17:
Remove the folder you created with rmdir command \\
Understand where you can't use rmdir by reading the manual \\
#+BEGIN_SRC
$ rmdir <folder_name>
$ man rmdir
#+END_SRC
Find how rm command works \\
#+BEGIN_SRC
$ rm <file_name>
#+END_SRC
Can you use it to delete folders that can't be deleted with rmdir? \\
If so how? \\
Message/Mail me your solutions.
* Exercise 12/5/17:
Find what the following command does by reading the manual
#+BEGIN_SRC
$ rm -r <folder_name>
#+END_SRC
Learn to use a text editor. \\
There are number of text editors available in most Linux Distributions \\
The most famous ones are vim, nano and emacs. \\
nano is very easy to learn \\
You can start learning vim by running the following command 
#+BEGIN_SRC
$ vimtutor
#+END_SRC
I recommend that you learn vim, it will be difficult initially but will make you work faster \\
You should by now be able to, \\
Create files, folders. \\
Delete files, folders. \\
Edit text files \\
Next exercise will be on 15/5/17. \\
You should be thorough with all the exercises till now to be able to do next week exercises.
